<h2> We're going to read in a dataset, inspect it, and take care of some preprocessing steps

In [2]:
import pandas

In [3]:
pandas.read_csv('C:/Users/jimfeter/Documents/Data.csv')

C:\Users\jimfeter\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2723: DtypeWarning: Columns (0,4,5,6,7,8,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Host: STWD,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Jan-Aug,Jimmy Feterman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Unique ID,Campaign Name,Publisher Name,Publisher,Social,Native,TravelEndemic,DSP,DSPTravel,Event Timestamp,Impression / Click Time,Revenue,Brand,SPG Tier
15,6.77E+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1452473407,1452465015,atm2.278.0,p1.4P,ul.G
16,6.13E+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1454104564,1453847835,atm2.290.56,p1.WI,ul.0
17,5.42E+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1454008490,1453821476,atm2.358.0,p1.AL,ul.G
18,3.03E+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1453864368,1453610612,atm2.721.5568866062545,p1.ST,ul.A
19,1.93E+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1452278277,1452123296,atm2.239.2,p1.WI,ul.0
20,7.87E+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1454163408,1453852077,atm2.957.0,p1.WI,ul.B
21,7.87E+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1454164915,1453852077,atm2.638.0,p1.WI,ul.B
22,8.04E+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1453501394,1452965067,atm2.164.0,p1.AL,ul.A
23,4.43E+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1451855510,1451533234,atm2.1077.0,p1.WI,ul.A
24,4.46E+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1453527667,1453356373,atm2.367.2,p1.SI,ul.0
25,5.66E+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1453069320,1452770284,atm2.1895.0,p1.AL,ul.0
26,8.16E+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1454020643,1454017119,atm2.249.0,p1.WI,ul.A
27,2.66E+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1452892114,1452791253,atm2.603.7940606974192,p1.WI,ul.0
28,3.65E+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1452142493,1451842494,atm2.478.0,p1.MD,ul.P
29,7.53E+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1452197324,1451915670,atm2.166.01,p1.SI,ul.A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171907,9.17e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1470943269,1470866846,atm2.191.2,p1.WH,ul.P
171908,6.53e+17,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1472362920,1472153520,atm2.715.92,p1.EL,ul.G
171909,2.61e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1470768252,1470406331,atm2.122.55,p1.SI,ul.A
171910,3.49e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1470678398,1470238405,atm2.320.0,p1.SI,ul.0
171911,6.43e+17,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1471017083,1470879499,atm2.682.08,p1.WI,ul.A
171912,1.34e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1471356737,1471281398,atm2.170.05,p1.WI,ul.G
171913,1.72e+17,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1472061109,1472052902,atm2.245.0,p1.SI,ul.0
171914,1.9e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1470355626,1470099686,atm2.165.75,p1.WI,ul.0
171915,8.64e+17,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1471621603,1471272547,atm2.113.05,p1.EL,ul.0
171916,8.83e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1471207346,1471028974,atm2.144.5,p1.SI,ul.0
171917,3.77e+17,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1470230620,1469729159,atm2.407.01,p1.SI,ul.G
171918,3.88e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1470394892,1470308314,atm2.238.0,p1.SI,ul.G
171919,7.38e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1470346664,1470069221,atm2.69.0,p1.SI,ul.0
171920,4.8e+17,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1470418131,1470265990,atm2.169.0,p1.WI,ul.0
171921,6.7e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1471270832,1470844160,atm2.409.64,p1.SI,ul.A
171922,3.95e+17,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1470365756,1469931537,atm2.949.4,p1.WI,ul.A
171923,2.04e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1470103193,1470077384,atm2.170.1,p1.SI,ul.0
171924,1.57e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1471021352,1470852682,atm2.420.994234672624,p1.SI,ul.0
171925,6.19e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1470941987,1470935012,atm2.205.63934140404015,p1.SI,ul.A
171926,2.32e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1471445877,1471008606,atm2.161.0,p1.WI,ul.0
171927,5.28e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1470161782,1470156059,atm2.1034.22,p1.WI,ul.A
171928,5.35e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1470515598,1470223100,atm2.566.08,p1.SI,ul.0
171929,3.54e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1471547519,1471280215,atm2.293.25,p1.SI,ul.G
171930,5.13e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1471371063,1471278953,atm2.138.0,p1.SI,ul.A
171931,4.78e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1472083109,1471801824,atm2.537.0,p1.SI,ul.0
171932,5.5e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1472429744,1472141722,atm2.135.2,p1.SI,ul.A
171933,7.14e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1471005069,1470668135,atm2.234.22,p1.4P,ul.A
171934,1.01e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1470317202,1470143796,atm2.239.40411354603555,p1.WI,ul.P
171935,1.01e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1470317539,1470143796,atm2.244.02,p1.4P,ul.P
171936,1.24e+18,[2016_WI_PP] Prospecting,Vivaki:AOD,[2016_WI_PP] ProspectingVivaki:AOD,0,0,0,1,0,1471208670,1470943318,atm2.169.0,p1.SI,ul.A

    That is not what we wanted..Look at the dataset and figure out why our data imported this way

In [4]:
#the preceding quesiton mark will show us all of the parameters we can use to get our data read in properly
?pandas.read_csv()

    The skiprows parameter should do the job

In [5]:
df = pandas.read_csv('C:/Users/jimfeter/Documents/Data.csv', skiprows = 15)
df.head(3)

,Unique ID,Campaign Name,Publisher Name,Publisher,Social,Native,TravelEndemic,DSP,DSPTravel,Event Timestamp,Impression / Click Time,Revenue,Brand,SPG Tier
0,6.770000e+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1452473407,1452465015,atm2.278.0,p1.4P,ul.G
1,6.130000e+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1454104564,1453847835,atm2.290.56,p1.WI,ul.0
2,5.420000e+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1454008490,1453821476,atm2.358.0,p1.AL,ul.G

    .describe() and .info() are two methods you can apply to your df to survey the dataframe

In [6]:
#useful for numeric data
df.describe()

,Unique ID,Social,Native,TravelEndemic,DSP,DSPTravel,Event Timestamp,Impression / Click Time
count,1.719220e+05,171922.000000,171922.000000,171922.000000,171922.000000,171922.000000,1.719220e+05,1.719220e+05
mean,4.612269e+18,0.029752,0.004956,0.248066,0.480497,0.208548,1.462559e+09,1.462434e+09
std,2.665449e+18,0.169902,0.070223,0.431892,0.499621,0.406272,5.908476e+06,5.910926e+06
min,9.980000e+13,0.000000,0.000000,0.000000,0.000000,0.000000,1.451625e+09,1.451080e+09
25%,2.300000e+18,0.000000,0.000000,0.000000,0.000000,0.000000,1.457307e+09,1.457126e+09
50%,4.600000e+18,0.000000,0.000000,0.000000,0.000000,0.000000,1.462374e+09,1.462280e+09
75%,6.930000e+18,0.000000,0.000000,0.000000,1.000000,0.000000,1.467895e+09,1.467782e+09
max,9.220000e+18,1.000000,1.000000,1.000000,1.000000,1.000000,1.472702e+09,1.472701e+09

In [7]:
#provides information on the datatypes present in the dataframe. 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171922 entries, 0 to 171921
Data columns (total 14 columns):
Unique ID                  171922 non-null float64
Campaign Name              171922 non-null object
Publisher Name             171922 non-null object
Publisher                  171922 non-null object
Social                     171922 non-null int64
Native                     171922 non-null int64
TravelEndemic              171922 non-null int64
DSP                        171922 non-null int64
DSPTravel                  171922 non-null int64
Event Timestamp            171922 non-null int64
Impression / Click Time    171922 non-null int64
Revenue                    171922 non-null object
Brand                      171588 non-null object
SPG Tier                   171588 non-null object
dtypes: float64(1), int64(7), object(6)
memory usage: 18.4+ MB

    data.info() showed us a few features that we categorized as the wrong datatypes.

In [8]:
#convert touch points to int datatype
df[['Native', 'Social', 'TravelEndemic','DSP', 'DSPTravel']] = df[['Native', 'Social', 'TravelEndemic','DSP', 'DSPTravel']].fillna(0).astype(int)

In [9]:
#drop columns we don't need
df = df.drop(['Event Timestamp', 'DSP', 'Impression / Click Time'], axis = 1)

    In the past we've had problem with bots clicking on ads thousands of times. Are there any bots in our data?

In [12]:
#How many unique people are in our dataset
df['Unique ID'].nunique()

2542

In [13]:
#Check if there is any one person with 'too many' touches
publisher_type = df[['Unique ID','Native', 'Social', 'TravelEndemic', 'DSPTravel']].groupby('Unique ID').sum()

#four each column other than Unique ID in the publisher_type, check the max touches
publisher_type = publisher_type.sort_values(['TravelEndemic'],ascending = False)

publisher_type.head(5)

              Native  Social  TravelEndemic  DSPTravel
Unique ID
4.830000e+18       4       2             77         39
1.370000e+18       0       4             76         40
6.920000e+18       3       9             69         40
5.580000e+18       0       3             69         30
8.440000e+18       1       7             68         29

In [14]:
#or here's a faster way
publisher_type.max()

Native            6
Social           18
TravelEndemic    77
DSPTravel        67
dtype: int32

In [91]:
df.head(2)

,Unique ID,Campaign Name,Publisher Name,Publisher,Social,Native,TravelEndemic,DSP,DSPTravel,Event Timestamp,Impression / Click Time,Revenue,Brand,SPG Tier
0,6.770000e+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1452473407,1452465015,atm2.278.0,p1.4P,ul.G
1,6.130000e+18,[2015_WI_BA] Resorts,AOL Network,[2015_WI_BA] ResortsAOL Network,0,0,0,1,0,1454104564,1453847835,atm2.290.56,p1.WI,ul.0